language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - data-quality
  - hotfix
  - bs3-with-grails3
  - develop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: nUPA6pOCRq8aWX981iMMEOGP+2J6rRgiaQAo3mjxn4AEB+1rfl903z53y6o4QU/YsrWHrZC8cLJObYK+ZWw0ndO5thOrL/cvO4Z+u8A/X1SuTdMIztuHGz5+xdMAqQuXGxK68zko3tcS9pmjS/inNPiXH5kHg1XlsYZ0HnWVnfP2kDcLrvVyu+R9p4ohaMcYrhcK3RCvJAE/VHr/npjYYf7HCflmrcOZLtBfSEez+8qoaGBOxI2BjLj7N5D3eMzsCEYrbYIWrRbTqEffLegRrc3+qeQ7tx2fW85SyuLMcHpBuQUAt4+jsrweA6tx3gh5ZSAWvhR4XCNMXeoGkhqGpNUbhZ74HdgssBBHixQpfQBmRIaQX5hAx6t+nIqBvBttbGEb5rNvSlKMCgQ9mmWF1khqASc9V/lYWQkr6OTb2P21QSecEE/uSYOwF7Qi/uDH45iA3DCXBL6+LKiJ9THiRQKxguSaIDPx79yWryNvh6160QtV/OYRKx/4wH6u4Z4hQAiIkzqTCLBa488VChIUEKw8DCCw+Pxhot9Oat6J9Ff6mZ8bKQOb46nyHI7wZTpib26FaQeH8ATs4EycMtMCOinRY4lkbZuJVqpmGIa8nGfqCoWBe1NtdGHlsK2g+U8KXC+0ViiK06YHzGSlpTA4nUPFK8dG4/U0UgC2gqNZy9g=
  - secure: ZL4bfBxPx2liTMWOD3gc247OGrJRgaUq68O3xyxRZfwAVcQKN3rXMXnXZukzOfswvcqnU9QGzTCDOlg89emopV/IgI35DsT+wVSOlIm+XvejdC1HeHLSx7X5QSCsiMXTBuvZG0ahTcpqf/OOf+6x2eUvyvqgborz1PDpXjehoSZo0I4UwEY5fo5C7GIRqxtZ4QGcqOdWSrIjE0Y65tRSYfVdrrHXxfLJpnGA6iwYyIGbw3rKsfaOo+VUi4KmIaO9KxlQKaPakkVqthAxgU2h5gyibOAhhfGw4HH/g0ofPTP49qFhkJRZtWUqM4rObU5ZDVfmUIHqv/J9Cn9TbUBCa6/njMjfuNcMXxhHnUsIDafLyxF+iIGYSb9dmTxtnSooAMVqCTMKLShmSpm+zkeCNvmtmSSNR1MHn7Ei7lUCEcFxgNzhvbu29iFdvuNPNCbwmd7rR5pFmDKUiFubRi4CyZYezoUouEuYtCqLCopxJvrymtlgqfL/tl+DlEmcjjwVyZJ+tvM4ZQ2ScKl2QT+byPtTz5mBFDJElgvx6VrYEsngUH7/NxTzuGDZbvaW4smbjWWxHDkd2GI3UqwGNt8pwLGA6m9mpcrSA8Pn+TCLhyEsncv8yutCQZKEgATXCKZtmgU5HF8zh8M7jzAwmaEusHc0uqrdgrToPlN+OLMQly8=
