language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - data-quality
  - hotfix
  - bs3-with-grails3
  - develop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
    - secure: "aOEfLoeScS4fTuqzcjwi/V2BJDEtTzmgmAm+rV4K24swoRsB1wGlEfxsj8k5F5+C0Y1YVoudBIRteI+xoEcVEZY+F3sbOXjkaF9uUi7OxBCSs9cYoDLhJNcyA37bU+LQ/O/NT3+uIwzS6ms8V79uyq+n1FDPm13YV4cXbkJASFn8uhZTk9uAlmSXOvC+KjxrZ+bXQh3na9XjKITdkQJeDZ5+5pCnPY+y9J/ZWbh8lc/ernzlt6EYPDsR1b1QE31BZWGI0kfRvEAUrE0jrK4jZy/9WecJq7OAs1P50sED+SuUDyO5ihHbS9u/Dz4H+vExcSM0B27443ivux10bPHSu+dwFsDqgx5bcbiZ3ioqTXRB2WlaoonoW1r5pCAR5DFd2MsUZYhj/Z6Xm50z+zXM9ug/sTK4g0nelyZaJFi04Sxf941nkjCr82udl9FwCCGkxoQIuWB6vSjpMIAAYFmobTy2Zuhk6XY46QW8sVHEVw/FVLsRCDZG049LOe9tnWoRr25z0i2464iB/rDDmu+/JETRJq3C1FFQuXojZjPKHgNaxvUUHU2FaJwA5OMVFktVzGCKGbUMJsVykqFWPieT8TqGFVs8UU27UDjFZCXpVTgKjDhaTYPrkaFpEABYbZipSCIBR6SrHnzH8MrlmSLIr/P+QmiRooIPRih9YEVtxnQ="
    - secure: "H49usOa6JMRxI/BFWHufcUc6MoEZ6N4LLv0BpFhiuH1p86LL0W3dbI1FxvmGUYNfLRn16lf1uyOK2LmOiczPW+yEBUgREQR3mvbTFLUGprcDD3BlHKo1Q5gXITKiGH2Hw0ES1a55huDCWQjesRCnb9KVKRzIhQMNmaH9OMYokp19nxHVsJ1Qp66DhhR/BZZ/yMq8gyXv/ksj2M6XorJDFcOLhqNzYu38EWF8M6IM8h0D7W9VFKheHqLqKwQ6/JLtGHSx2LQpY5MS89uOD41hYfwLXviApfGXfUy8LiSiPactB4Wb4lT0jjyCMVx5KgrRzcj+eFgqo/L641aCf/5RoAK1Q5Lj/KF5krLGFz6rpiUJ1DZ8CNvdrnA/1bmKgkoGr9ZkYFH6wHbRSEG1odboQfWvjVtfYhvErYIfYk4K+bIUHBc2WeFb63sdea025eWRAHKTiAFZspftbiVe/rBL9Fhd/qPn2ebSl/hT7D9kHg5B8gy+i4O+Z71Tr4wuCbnT3i8SxhskMUQDMmOIwIpX6IKDsm/0uEohLgtQt/zYxkcd/DmZwSTKkisjegcwug68IERIX4tZV3y2yD2TaIiZO4ljrJDAuKMRC/xw1itII1tXR9yCnoi8ORFpBEKC2BjhvSy/ajHeqtxsTxEJiksuqhwHForscUCVEfNvGpEip9w="
